### ISSUE TITLE
Include example files that the /samples/ were generated from

### ISSUE THREAD

**Issue by josiahseaman** [wapiflapi/binglide#5]
I love this work.  Absolutely fascinating.  Would you please include the original image/data files you used to generate the samples?  I specifically interested in the source of this example: https://raw.githubusercontent.com/wapiflapi/binglide/master/samples/rgb2_24b.bmp_3g.png

**Comment by wapiflapi** [comment]
Thank you for your interest. I added the source files I used to generate the samples. It was a bit of a mess so this might be incomplete. You should be able to reproduce the results though.

This is the one for the analysis you are specifically interested in: https://github.com/wapiflapi/binglide/blob/caf6e9964636c3b43bcb89639fbfd3c73afb06b7/samples/source/rgb2_24b.bmp

It's 24b bmp, which means three channels (R G B), the rendering you are looking at is a 3-gram analysis, so it will sample RGB; GBR and BRG variations, that's the three branches you can see on the picture.

**Comment by josiahseaman** [comment]
Thanks for the fast response.  You're the best.  I will be looking at this
more once I get back from Pycon.
